Add draggy number input
opensight-cv/frontend pull request #2
Opened 2020-04-30 14:39 UTC by g10ria

Component takes a speed option, set to an integer for integer input and a real number for float input

2020-05-01 10:16 UTC, 132ikl commented
Can you make these changes:
* Fix the arrows
* Disable dragging when in manual edit mode
* Hide the default number-type input arrows on Firefox (https://ikl.sh/taCd)
* Separate speed and type control (just add a "float" parameter with boolean value)
* Rename speed to step for clarity

2020-05-01 10:16 UTC, 132ikl requested changes
Can you make these changes:
* Fix the arrows
* Disable dragging when in manual edit mode
* Hide the default number-type input arrows on Firefox (https://ikl.sh/taCd)
* Separate speed and type control (just add a "float" parameter with boolean value)
* Rename speed to step for clarity

2020-05-01 23:48 UTC, g10ria commented
What do you mean by fix the arrows?

2020-05-01 23:49 UTC, 132ikl commented
The increment/decrement arrows on the left/right don't work for me on Chrome or Firefox.

2020-05-01 23:51 UTC, g10ria commented
Oh huhh that's weird. Ok I'll look into it

2020-05-02 06:43 UTC, 132ikl approved these changes

2020-05-02 11:36 UTC, 132ikl requested changes
Can you make sure that the pipeline update event isn't sent until the user releases dragging? Currently each step sends an update to the backend.

2020-05-03 05:02 UTC, 132ikl approved these changes

2020-05-03 15:19 UTC, carbotaniuman requested changes

2020-05-03 15:19 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragFloatOption.vue
> +export default class DragIntegerOption extends DragNumberOption {
I think you need an `@Component` here.

2020-05-03 15:19 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragIntegerOption.vue
> +export default class DragIntegerOption extends DragNumberOption {
I think you need an `@Component` here.

2020-05-03 15:19 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragNumberOption.vue
> +    const moveListener = this.handleMouseMove.bind(this);
Why not an arrow function?

2020-05-03 15:19 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragNumberOption.vue
> +    if (this.option.defaultValue) this.displayValue = this.option.defaultValue;
this.value (the prop) gets set with the right value at some point in time. Idk if it's at  `mounted()` or `created()`, but Baklava already has that built in, so let's use it.

2020-05-07 01:32 UTC, 132ikl commented
Can you do the following in order to fix up the history:
1. Reset to `96a88f7`
2. Pull with rebase option
3. Cherry-pick f7d5ad3
4. Force push

2020-05-07 01:33 UTC, 132ikl requested changes
Can you change it to make sure that if the min/max is not set then it is not limited?

2020-05-07 21:40 UTC, 132ikl approved these changes

2020-05-08 19:39 UTC, carbotaniuman requested changes

2020-05-08 19:39 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragIntegerOption.vue
> + *      defaults to -100
Outdated.

2020-05-08 19:39 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragFloatOption.vue
> + * max - maximum value
Outdated.

2020-05-08 19:39 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragNumberOption.vue
> +      if (this instanceof DragIntegerOption) this.tempValue = this.displayValue.toFixed(0);
tempValue never gets used anywhere? is this meant to be displayValue?

2020-05-08 19:39 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragNumberOption.vue
> +    if (this.option.min) ret = Math.max(this.option.min, ret);
test for `=== undefined`, these prevent 0 mins and maxes

2020-05-08 19:39 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragNumberOption.vue
> +    if (this.option.max) ret = Math.min(this.option.max, ret);
test for `=== undefined`, these prevent 0 mins and maxes

2020-05-09 03:41 UTC, carbotaniuman commented on src/components/baklava-options-plugin/DragNumberOption.vue
> +      if (this instanceof DragIntegerOption) this.tempValue = this.displayValue.toFixed(0);
Looks like it's inherited? Just verify its correct.

2020-07-07 21:29 UTC, carbotaniuman approved these changes
LGTM

2020-07-07 21:34 UTC, merged